apiVersion: apps/v1 # גרסת ה-API
kind: Deployment # סוג האובייקט - פריסת שרת
metadata:
  name: backend # שם השרת
  namespace: barsuf # מרחב השמות
  labels:
    app: backend # תגית זיהוי
spec:
  replicas: 1 # עותק אחד של השרת מספיק
  selector:
    matchLabels:
      app: backend # איך למצוא את העותקים של השרת
  template:
    metadata:
      labels:
        app: backend # תגית לכל עותק (Pod)
    spec:
      containers:
        - name: backend # שם המכולה
          image: barsuf-backend:latest # תמונת הקוד של השרת
          imagePullPolicy: Never # להשתמש בתמונה מקומית בלבד
          ports:
            - containerPort: 3001 # השרת מאזין לפורט 3001
          volumeMounts:
            - name: barsuf-data # שם האחסון לחיבור
              mountPath: /app/server/data # לאיפה בתוך המכולה לחבר את האחסון (תיקיית הנתונים)
      volumes:
        - name: barsuf-data # הגדרת האחסון
          persistentVolumeClaim:
            claimName: barsuf-data-pvc # שם הדרישה לאחסון קבוע (כדי שהמידע לא יימחק בכיבוי)

---
apiVersion: v1 # גרסת ה-API
kind: Service # שירות שמאפשר תקשורת עם השרת
metadata:
  name: backend-service # שם השירות
  namespace: barsuf # מרחב השמות
spec:
  selector:
    app: backend # לאיזה עותקים לשלוח בקשות
  ports:
    - protocol: TCP # פרוטוקול
      port: 3001 # הפורט של השירות
      targetPort: 3001 # הפורט בתוך המכולה
