---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: barsuf-data-pvc
  namespace: barsuf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data-pvc
  namespace: barsuf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
