---
apiVersion: v1 # גרסת ה-API
kind: PersistentVolumeClaim # דרישה לאחסון קבוע
metadata:
  name: barsuf-data-pvc # שם הדרישה (משמש את השרת כדי לשמור קבצים)
  namespace: barsuf # מרחב השמות
spec:
  accessModes:
    - ReadWriteOnce # מאפשר קריאה וכתיבה על ידי עותק אחד של השרת
  resources:
    requests:
      storage: 5Gi # נפח האחסון המבוקש (5 ג'יגה מספיק למסמכים ותמונות)
