name: Deploy to Cloud Run

on:
  push:
    branches:
      - main # רץ בכל פעם שדוחפים קוד ל-main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}' # המפתח הסודי שתוסיף בגיטהאב

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          # בניית האימג' של האתר ודחיפה למחסן של גוגל
          docker build -t us-central1-docker.pkg.dev/project-e7b25b42-8e43-4df1-8ce/cloud-run-source-deploy/barsuf:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/project-e7b25b42-8e43-4df1-8ce/cloud-run-source-deploy/barsuf:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          # פריסה סופית לענן
          gcloud run deploy barsuf \
            --image us-central1-docker.pkg.dev/project-e7b25b42-8e43-4df1-8ce/cloud-run-source-deploy/barsuf:${{ github.sha }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
